{% set version = "1.7" %}

package:
  name: pyaudi
  version: {{ version }}

source:
  url: https://github.com/darioizzo/audi/archive/v{{ version }}.tar.gz 
  sha256: ca91599a11796f56739a1310838cda976b9882eab5565965cc0b14923f3e5488

build:
  number: 0
  skip: true  # [win]
  
requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake

  host:
    - boost
    - eigen
    - piranha 0.11
    - mppp 0.12
    - audi {{ version }}
    - python
    - gmp
    - mpfr

  run:
    - boost 
    - python
    - gmp 
    - mpfr

about:
  home: http://darioizzo.github.io/audi/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'Python exposition of the audi C++ library: Algebra of Taylor truncated polynomials and a few algorithms useful for its applications (e.g. Automated differentiation, Differential Intelligence, Taylor Models, etc.)'

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
