{% set version = "1.9.1" %}

package:
  name: pyaudi
  version: {{ version }}

source:
  url: https://github.com/darioizzo/audi/archive/v{{ version }}.tar.gz
  sha256: a79841855bcb06fd63e1710c6537abc56d8c9105574aafd82b4f566efa19aa9e

build:
  number: 0
  skip: true  # [py<36]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - clang  # [win]
    - ninja  # [win]

  host:
    - python
    - eigen
    - obake-devel
    - mppp
    - audi {{ version }}
    #- pybind11

  run:
    - python
    - numpy

about:
  home: http://darioizzo.github.io/audi/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'Python exposition of the audi C++ library: Algebra of Taylor truncated polynomials and a few algorithms useful for its applications (e.g. Automated differentiation, Differential Intelligence, Taylor Models, etc.)'

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
