travis:
  secure:
    BINSTAR_TOKEN: V7ktUPrG6glP9eh8RcSGnhGa90TCJln8cC0sVuSqfJ4iY7e1d1jyfg8rN4w6FVe6dv6VWq96XAO58kz/CrfohHBtmySxj3njj1GWXTWM5eI2mXlxblcT9rrEN818RzoF9aGQEQk+Sz4NMawElinKFoVDpf93DoDgI2HU1L7lPVfd7VsI5KWEoFovS04f7Thosq2Byj+gPn/yUwcs/kw8T1r+xg6Z71DT2uB4PyFWGXN9qdYGZkLZCSZKDFBiA6wIbahaXbO99JYf82LBjpJGzOKuDWurpvDRjSzOu+9wbk4IHbSpjdNAbjKc60Yf3gorero3bOtZVG5z2Fr+jMDxab1tVTC6XAgob7jBMoLpEx7bmwmhJWF7YKE/P9/AJifcG1cPBt2S6mAqyojWM5gC0Nc6vm4Mi2Khb2rdVU8AVhbkQcVLIp64Xg3MFQ0HLE6UVx5MizddaDlPInUo9220dKxc6xzVQ0DfSy0yI+1LLSvD3eoK1mNr3fz6DJtWvR9sfT2DXIhl7i+qFInXuf5EBH3GCC5RUTFMrS5FhLZIL+QM2MeOyAU2Y2rlDqXz9kT7s9N0gONekr7m1i21aGwUf6UCb6bu8rs6LyctkYgb3MmpxvDZNMLIifYu9lXJFtbsqoHaSbzULkbyDnkuuLcHKb2Ak8czqwaB2yrRxnTOq7M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
